---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openchami
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
  source:
    # These must match the private repo path. The demo requires copying the
    # full example-local directory into the private repo, rather than its
    # contents into the top level of the private repo.
    path: 'example-local/services'
    repoURL: 'https://github.com/vbhogadi-oss/kube-deploy'
    targetRevision: main
  destination:
    namespace: openchami
    server: 'https://kubernetes.default.svc'
